# -*- coding: utf-8 -*-
"""24AI60R43_Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRKgFtYH5_sCA3SMVHEqwQnD6yfZK60M
"""

#Fuction for Reading the file
def read_f(file_name):
  data=[] #listing which contain key , value as tuple
  with open(file_name) as f:
    for index in f:
      key , value=index.split('\t')
      data.append((str(key), int(value)))
  return data

#reading the data from file given
data=read_f('data-2col.txt')
print(data)

# heapify fuction from root to leaves
def heapify(arr, n, i):
  largest=i #lasgest as root
  l=2*i+1 #left child
  r=2*i+2 #right child


  if l<n and arr[largest][1]<arr[l][1]:
    largest=l
  if r<n and arr[largest][1]<arr[r][1]:
    largest=r

  if largest!=i:
    arr[i], arr[largest]=arr[largest], arr[i]
    heapify(arr, n, largest)

#fuction for build heap

def build_heap(arr):
  n=len(arr)
  for i in range(n//2-1, -1, -1):
    heapify(arr, n, i)
  return arr

#calling the Build heap function
data1=data
max_heap=build_heap(data1)
print(max_heap)

#fuction for extracting max element
def extract_max(arr,n):
  #n=len(arr)
  maxi=arr[0]
  arr[0], arr[n-1]=arr[n-1], arr[0]
  heapify(arr, n-1, 0)

  return arr, maxi

#function for finding key associated with kth largest

def kth_largest(arr, k):
  for i in range(0,k):
    arr, maxi=extract_max(arr, len(arr)-i)
    print(f'{i}th maximums is: {maxi}')

  return arr[0][0]

#calling and printing upto k-1 largest element key ,value and kth largest element key
data2=data
max_heap=build_heap(data2)
kth_maximum=kth_largest(max_heap,11 )
print(f'key of kth maximum is: {kth_maximum}')

#function for sorting the element in descending order
#implementing heap sort using heapify func
def heap__sort(arr):
  n=len(arr)
  for i in range(n-1, 0, -1):
    arr[i], arr[0]=arr[0], arr[i]
    heapify(arr, i, 0)

  return arr[::-1] #for traversing the  list from end to start index

#calling the heap sort fuction
data3=data
heap__sort(data3)
print(data3) #printing after sorting

#heapify fuction from leaves to toward root
def heapifyup(arr, index):

  parent=(index-1)//2

  while index>0 and arr[index][1]>arr[parent][1]:
    arr[index], arr[parent]=arr[parent], arr[index]
    index=parent
    parent=(index-1)//2

#fuction for returning top k element under the condition of memeory limit of k elements

#k element max heap with all element are top k element among all the data point


def max_heap_with_k_element(data, k):
  n=len(data)
  max_heap_new=[]

  #building heap with k element
  data1=data[:k]
  max_heap_new=build_heap(data1)

  #traversing and remaining element and finding a maximum element if exit
  for i in range(k,n):

    min_ind=k//2
    for j in range(k//2+1,k):
      if(max_heap_new[min_ind][1]>max_heap_new[j][1]):
        min_ind=j
    #swaping the least elemet from heap with its greater element in reamaining list
    if(data[i][1]>max_heap_new[min_ind][1]):
      max_heap_new[min_ind]=data[i]
      heapifyup(max_heap_new, min_ind)

  return max_heap_new #returning the max heap with size k

#calling the maxheap func for size k
data4=data
k_element_max_heap = max_heap_with_k_element(data4, 10) # assuming k as 10
print(k_element_max_heap)

